library(deque)

x <- deque()
str(x)
push(x, 1)
push(x, 2)
stopifnot(identical(pop(x), 2))
stopifnot(identical(pop(x), 1))
stopifnot(is.null(pop(x)))
unshift(x, "a")
unshift(x, "b")
unshift(x, "c")
str(x)
stopifnot(identical(pop(x), "a"))
stopifnot(identical(pop(x), "b"))
stopifnot(identical(pop(x), "c"))
stopifnot(is.null(pop(x)))
str(x)
push(x, 1)
push(x, 2)
push(x, 3)
unshift(x, "a")
str(x)
stopifnot(identical(shift(x), "a"))
stopifnot(identical(shift(x), 1))
stopifnot(identical(shift(x), 2))
stopifnot(identical(shift(x), 3))

y <- deque()
str(y)
push(y, 1)
unshift(y, "a")
stopifnot(is.null(pop(x)))
stopifnot(is.null(shift(x)))


z <- list("a", "b")
push(x, z)
stopifnot(identical(pop(x), z))
stopifnot(is.null(pop(x)))
push(x, z)
stopifnot(identical(shift(x), z))
stopifnot(is.null(pop(x)))
unshift(x, z)
stopifnot(identical(shift(x), z))
stopifnot(is.null(shift(x)))
unshift(x, z)
stopifnot(identical(pop(x), z))
stopifnot(is.null(shift(x)))
